// ==============================================================================
// @file: frontend/src/lib/benchmarkData.ts
// @project: GeoSync — AI-Powered Geospatial Middleware
// @description: Master 37-Parcel Benchmark Ground-Truth Dataset for instant demo fidelity.
// ==============================================================================

import type { FeatureCollection } from "geojson";

export interface BenchmarkParcel {
  id: string;
  khasra_no: string;
  owner_name: string;
  village: string;
  tehsil: string;
  alignment_status: string;
  confidence_band: string;
  ulpin: string;
  area_sqm: number;
  area_bigha: number;
  alignment_confidence: number;
  situation: string;
  reason: string;
  status_color: string;
}

// 37 Known Cadastral Blocks (from DILRMP 3.0 Ground-Truth specification)
export const BENCHMARK_37_PARCELS: BenchmarkParcel[] = [
  {
    id: "par-36475-0",
    khasra_no: "36475",
    owner_name: "Khatedar (Kh. 36475)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "GOVT_ILLEGAL",
    confidence_band: "RED",
    ulpin: "ULPIN-UP-2026-36475",
    area_sqm: 8390.2,
    area_bigha: 3.32,
    alignment_confidence: 52.1,
    situation: "सरकारी भूमि / अवैध कब्जा",
    reason: "Govt. Land / Encroachment - State Property Verification Required",
    status_color: "red",
  },
  {
    id: "par-5827269-1",
    khasra_no: "5827269",
    owner_name: "Khatedar (Kh. 5827269)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "VERIFIED_CLEAR",
    confidence_band: "GREEN",
    ulpin: "ULPIN-UP-2026-5827269",
    area_sqm: 7726.3,
    area_bigha: 3.05,
    alignment_confidence: 97.4,
    situation: "सही (Verified Clear)",
    reason: "Verified Clear - Undisputed Legal Cadastral Parcel",
    status_color: "green",
  },
  {
    id: "par-272-4",
    khasra_no: "272",
    owner_name: "Khatedar (Kh. 272)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "OCCLUDED",
    confidence_band: "AMBER",
    ulpin: "ULPIN-UP-2026-272",
    area_sqm: 6467.0,
    area_bigha: 2.56,
    alignment_confidence: 76.5,
    situation: "ओकल्शन (पेड़ / छाया)",
    reason: "Tree Occultation / Canopy Shadow - High Ground Discrepancy",
    status_color: "amber",
  },
  {
    id: "par-656565-3",
    khasra_no: "656565",
    owner_name: "Khatedar (Kh. 656565)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "VERIFIED_CLEAR",
    confidence_band: "GREEN",
    ulpin: "ULPIN-UP-2026-656565",
    area_sqm: 22208.4,
    area_bigha: 8.78,
    alignment_confidence: 96.8,
    situation: "सही (Verified Clear)",
    reason: "Verified Clear - Undisputed Legal Cadastral Parcel",
    status_color: "green",
  },
  {
    id: "par-1-4",
    khasra_no: "1",
    owner_name: "Khatedar (Kh. 1)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "GOVT_ILLEGAL",
    confidence_band: "RED",
    ulpin: "ULPIN-UP-2026-1",
    area_sqm: 23587.2,
    area_bigha: 9.33,
    alignment_confidence: 48.6,
    situation: "सरकारी भूमि / अवैध कब्जा",
    reason: "Govt. Land / Encroachment - State Property Verification Required",
    status_color: "red",
  },
  {
    id: "par-57-5",
    khasra_no: "57",
    owner_name: "Khatedar (Kh. 57)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "GOVT_ILLEGAL",
    confidence_band: "RED",
    ulpin: "ULPIN-UP-2026-57",
    area_sqm: 3091.7,
    area_bigha: 1.22,
    alignment_confidence: 54.2,
    situation: "सरकारी भूमि / अवैध कब्जा",
    reason: "Govt. Land / Encroachment - State Property Verification Required",
    status_color: "red",
  },
  {
    id: "par-345-6",
    khasra_no: "345",
    owner_name: "Khatedar (Kh. 345)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "OCCLUDED",
    confidence_band: "AMBER",
    ulpin: "ULPIN-UP-2026-345",
    area_sqm: 4120.5,
    area_bigha: 1.63,
    alignment_confidence: 78.1,
    situation: "ओकल्शन (पेड़ / छाया)",
    reason: "Tree Occultation / Canopy Shadow - High Ground Discrepancy",
    status_color: "amber",
  },
  {
    id: "par-45454-7",
    khasra_no: "45454",
    owner_name: "Khatedar (Kh. 45454)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "GOVT_ILLEGAL",
    confidence_band: "RED",
    ulpin: "ULPIN-UP-2026-45454",
    area_sqm: 5412.0,
    area_bigha: 2.14,
    alignment_confidence: 50.8,
    situation: "सरकारी भूमि / अवैध कब्जा",
    reason: "Govt. Land / Encroachment - State Property Verification Required",
    status_color: "red",
  },
  {
    id: "par-895-8",
    khasra_no: "895",
    owner_name: "Khatedar (Kh. 895)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "GOVT_ILLEGAL",
    confidence_band: "RED",
    ulpin: "ULPIN-UP-2026-895",
    area_sqm: 2980.0,
    area_bigha: 1.18,
    alignment_confidence: 51.5,
    situation: "सरकारी भूमि / अवैध कब्जा",
    reason: "Govt. Land / Encroachment - State Property Verification Required",
    status_color: "red",
  },
  {
    id: "par-57360-9",
    khasra_no: "57360",
    owner_name: "Khatedar (Kh. 57360)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "VERIFIED_CLEAR",
    confidence_band: "GREEN",
    ulpin: "ULPIN-UP-2026-57360",
    area_sqm: 3410.5,
    area_bigha: 1.35,
    alignment_confidence: 95.0,
    situation: "सही (Verified Clear)",
    reason: "Verified Clear - Undisputed Legal Cadastral Parcel",
    status_color: "green",
  },
  {
    id: "par-12-10",
    khasra_no: "12",
    owner_name: "Khatedar (Kh. 12)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "OCCLUDED",
    confidence_band: "AMBER",
    ulpin: "ULPIN-UP-2026-12",
    area_sqm: 6100.0,
    area_bigha: 2.41,
    alignment_confidence: 74.2,
    situation: "ओकल्शन (पेड़ / छाया)",
    reason: "Tree Occultation / Canopy Shadow - High Ground Discrepancy",
    status_color: "amber",
  },
  {
    id: "par-123-11",
    khasra_no: "123",
    owner_name: "Khatedar (Kh. 123)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "OCCLUDED",
    confidence_band: "AMBER",
    ulpin: "ULPIN-UP-2026-123",
    area_sqm: 4890.0,
    area_bigha: 1.93,
    alignment_confidence: 79.0,
    situation: "ओकल्शन (पेड़ / छाया)",
    reason: "Tree Occultation / Canopy Shadow - High Ground Discrepancy",
    status_color: "amber",
  },
  {
    id: "par-610-12",
    khasra_no: "610",
    owner_name: "Khatedar (Kh. 610)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "OCCLUDED",
    confidence_band: "AMBER",
    ulpin: "ULPIN-UP-2026-610",
    area_sqm: 3820.0,
    area_bigha: 1.51,
    alignment_confidence: 75.4,
    situation: "ओकल्शन (पेड़ / छाया)",
    reason: "Tree Occultation / Canopy Shadow - High Ground Discrepancy",
    status_color: "amber",
  },
  {
    id: "par-987-13",
    khasra_no: "987",
    owner_name: "Khatedar (Kh. 987)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "OCCLUDED",
    confidence_band: "AMBER",
    ulpin: "ULPIN-UP-2026-987",
    area_sqm: 4500.0,
    area_bigha: 1.78,
    alignment_confidence: 77.2,
    situation: "ओकल्शन (पेड़ / छाया)",
    reason: "Tree Occultation / Canopy Shadow - High Ground Discrepancy",
    status_color: "amber",
  },
  {
    id: "par-357-14",
    khasra_no: "357",
    owner_name: "Khatedar (Kh. 357)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "OCCLUDED",
    confidence_band: "AMBER",
    ulpin: "ULPIN-UP-2026-357",
    area_sqm: 4950.0,
    area_bigha: 1.96,
    alignment_confidence: 76.0,
    situation: "ओकल्शन (पेड़ / छाया)",
    reason: "Tree Occultation / Canopy Shadow - High Ground Discrepancy",
    status_color: "amber",
  },
  {
    id: "par-555-15",
    khasra_no: "555",
    owner_name: "Khatedar (Kh. 555)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "VERIFIED_CLEAR",
    confidence_band: "GREEN",
    ulpin: "ULPIN-UP-2026-555",
    area_sqm: 5120.0,
    area_bigha: 2.02,
    alignment_confidence: 96.0,
    situation: "सही (Verified Clear)",
    reason: "Verified Clear - Undisputed Legal Cadastral Parcel",
    status_color: "green",
  },
  {
    id: "par-777-16",
    khasra_no: "777",
    owner_name: "Khatedar (Kh. 777)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "OCCLUDED",
    confidence_band: "AMBER",
    ulpin: "ULPIN-UP-2026-777",
    area_sqm: 5300.0,
    area_bigha: 2.10,
    alignment_confidence: 73.9,
    situation: "ओकल्शन (पेड़ / छाया)",
    reason: "Tree Occultation / Canopy Shadow - High Ground Discrepancy",
    status_color: "amber",
  },
  {
    id: "par-144-17",
    khasra_no: "144",
    owner_name: "Khatedar (Kh. 144)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "GOVT_ILLEGAL",
    confidence_band: "RED",
    ulpin: "ULPIN-UP-2026-144",
    area_sqm: 4200.0,
    area_bigha: 1.66,
    alignment_confidence: 49.2,
    situation: "सरकारी भूमि / अवैध कब्जा",
    reason: "Govt. Land / Encroachment - State Property Verification Required",
    status_color: "red",
  },
  {
    id: "par-581-18",
    khasra_no: "581",
    owner_name: "Khatedar (Kh. 581)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "OCCLUDED",
    confidence_band: "AMBER",
    ulpin: "ULPIN-UP-2026-581",
    area_sqm: 3950.0,
    area_bigha: 1.56,
    alignment_confidence: 75.1,
    situation: "ओकल्शन (पेड़ / छाया)",
    reason: "Tree Occultation / Canopy Shadow - High Ground Discrepancy",
    status_color: "amber",
  },
  {
    id: "par-321-19",
    khasra_no: "321",
    owner_name: "Khatedar (Kh. 321)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "OCCLUDED",
    confidence_band: "AMBER",
    ulpin: "ULPIN-UP-2026-321",
    area_sqm: 4180.0,
    area_bigha: 1.65,
    alignment_confidence: 74.8,
    situation: "ओकल्शन (पेड़ / छाया)",
    reason: "Tree Occultation / Canopy Shadow - High Ground Discrepancy",
    status_color: "amber",
  },
  {
    id: "par-233-20",
    khasra_no: "233",
    owner_name: "Khatedar (Kh. 233)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "OCCLUDED",
    confidence_band: "AMBER",
    ulpin: "ULPIN-UP-2026-233",
    area_sqm: 6850.0,
    area_bigha: 2.71,
    alignment_confidence: 78.4,
    situation: "ओकल्शन (पेड़ / छाया)",
    reason: "Tree Occultation / Canopy Shadow - High Ground Discrepancy",
    status_color: "amber",
  },
  {
    id: "par-6767-21",
    khasra_no: "6767",
    owner_name: "Khatedar (Kh. 6767)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "GOVT_ILLEGAL",
    confidence_band: "RED",
    ulpin: "ULPIN-UP-2026-6767",
    area_sqm: 3200.0,
    area_bigha: 1.27,
    alignment_confidence: 53.0,
    situation: "सरकारी भूमि / अवैध कब्जा",
    reason: "Govt. Land / Encroachment - State Property Verification Required",
    status_color: "red",
  },
  {
    id: "par-25-22",
    khasra_no: "25",
    owner_name: "Khatedar (Kh. 25)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "GOVT_ILLEGAL",
    confidence_band: "RED",
    ulpin: "ULPIN-UP-2026-25",
    area_sqm: 2850.0,
    area_bigha: 1.13,
    alignment_confidence: 50.1,
    situation: "सरकारी भूमि / अवैध कब्जा",
    reason: "Govt. Land / Encroachment - State Property Verification Required",
    status_color: "red",
  },
  {
    id: "par-682-23",
    khasra_no: "682",
    owner_name: "Khatedar (Kh. 682)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "OCCLUDED",
    confidence_band: "AMBER",
    ulpin: "ULPIN-UP-2026-682",
    area_sqm: 3450.0,
    area_bigha: 1.36,
    alignment_confidence: 77.0,
    situation: "ओकल्शन (पेड़ / छाया)",
    reason: "Tree Occultation / Canopy Shadow - High Ground Discrepancy",
    status_color: "amber",
  },
  {
    id: "par-999-24",
    khasra_no: "999",
    owner_name: "Khatedar (Kh. 999)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "VERIFIED_CLEAR",
    confidence_band: "GREEN",
    ulpin: "ULPIN-UP-2026-999",
    area_sqm: 4620.0,
    area_bigha: 1.83,
    alignment_confidence: 96.5,
    situation: "सही (Verified Clear)",
    reason: "Verified Clear - Undisputed Legal Cadastral Parcel",
    status_color: "green",
  },
  {
    id: "par-58627-25",
    khasra_no: "58627",
    owner_name: "Khatedar (Kh. 58627)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "OCCLUDED",
    confidence_band: "AMBER",
    ulpin: "ULPIN-UP-2026-58627",
    area_sqm: 4320.0,
    area_bigha: 1.71,
    alignment_confidence: 76.1,
    situation: "ओकल्शन (पेड़ / छाया)",
    reason: "Tree Occultation / Canopy Shadow - High Ground Discrepancy",
    status_color: "amber",
  },
  {
    id: "par-69572-26",
    khasra_no: "69572",
    owner_name: "Khatedar (Kh. 69572)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "OCCLUDED",
    confidence_band: "AMBER",
    ulpin: "ULPIN-UP-2026-69572",
    area_sqm: 4890.0,
    area_bigha: 1.93,
    alignment_confidence: 75.8,
    situation: "ओकल्शन (पेड़ / छाया)",
    reason: "Tree Occultation / Canopy Shadow - High Ground Discrepancy",
    status_color: "amber",
  },
  {
    id: "par-628-27",
    khasra_no: "628",
    owner_name: "Khatedar (Kh. 628)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "VERIFIED_CLEAR",
    confidence_band: "GREEN",
    ulpin: "ULPIN-UP-2026-628",
    area_sqm: 4710.0,
    area_bigha: 1.86,
    alignment_confidence: 97.2,
    situation: "सही (Verified Clear)",
    reason: "Verified Clear - Undisputed Legal Cadastral Parcel",
    status_color: "green",
  },
  {
    id: "par-555b-28",
    khasra_no: "555-B",
    owner_name: "Khatedar (Kh. 555-B)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "VERIFIED_CLEAR",
    confidence_band: "GREEN",
    ulpin: "ULPIN-UP-2026-555B",
    area_sqm: 4180.0,
    area_bigha: 1.65,
    alignment_confidence: 98.0,
    situation: "सही (Verified Clear)",
    reason: "Verified Clear - Undisputed Legal Cadastral Parcel",
    status_color: "green",
  },
  {
    id: "par-5927-29",
    khasra_no: "5927",
    owner_name: "Khatedar (Kh. 5927)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "VERIFIED_CLEAR",
    confidence_band: "GREEN",
    ulpin: "ULPIN-UP-2026-5927",
    area_sqm: 4950.0,
    area_bigha: 1.96,
    alignment_confidence: 96.1,
    situation: "सही (Verified Clear)",
    reason: "Verified Clear - Undisputed Legal Cadastral Parcel",
    status_color: "green",
  },
  {
    id: "par-0-30",
    khasra_no: "Kh.0",
    owner_name: "Gram Sabha Community Pool",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "VERIFIED_CLEAR",
    confidence_band: "GREEN",
    ulpin: "ULPIN-UP-2026-000",
    area_sqm: 14200.0,
    area_bigha: 5.61,
    alignment_confidence: 99.1,
    situation: "सही (Verified Clear)",
    reason: "Verified Clear - Gram Sabha Pond & Commons",
    status_color: "green",
  },
  {
    id: "par-377-31",
    khasra_no: "377",
    owner_name: "Khatedar (Kh. 377)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "VERIFIED_CLEAR",
    confidence_band: "GREEN",
    ulpin: "ULPIN-UP-2026-377",
    area_sqm: 3820.0,
    area_bigha: 1.51,
    alignment_confidence: 97.4,
    situation: "सही (Verified Clear)",
    reason: "Verified Clear - Undisputed Legal Cadastral Parcel",
    status_color: "green",
  },
  {
    id: "par-222-32",
    khasra_no: "222",
    owner_name: "Khatedar (Kh. 222)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "VERIFIED_CLEAR",
    confidence_band: "GREEN",
    ulpin: "ULPIN-UP-2026-222",
    area_sqm: 2950.0,
    area_bigha: 1.17,
    alignment_confidence: 98.2,
    situation: "सही (Verified Clear)",
    reason: "Verified Clear - Undisputed Legal Cadastral Parcel",
    status_color: "green",
  },
  {
    id: "par-2555-33",
    khasra_no: "2555",
    owner_name: "Khatedar (Kh. 2555)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "VERIFIED_CLEAR",
    confidence_band: "GREEN",
    ulpin: "ULPIN-UP-2026-2555",
    area_sqm: 3120.0,
    area_bigha: 1.23,
    alignment_confidence: 97.0,
    situation: "सही (Verified Clear)",
    reason: "Verified Clear - Undisputed Legal Cadastral Parcel",
    status_color: "green",
  },
  {
    id: "par-888-34",
    khasra_no: "888",
    owner_name: "Khatedar (Kh. 888)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "VERIFIED_CLEAR",
    confidence_band: "GREEN",
    ulpin: "ULPIN-UP-2026-888",
    area_sqm: 3640.0,
    area_bigha: 1.44,
    alignment_confidence: 98.4,
    situation: "सही (Verified Clear)",
    reason: "Verified Clear - Undisputed Legal Cadastral Parcel",
    status_color: "green",
  },
  {
    id: "par-106-35",
    khasra_no: "106",
    owner_name: "Khatedar (Kh. 106)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "VERIFIED_CLEAR",
    confidence_band: "GREEN",
    ulpin: "ULPIN-UP-2026-106",
    area_sqm: 4190.0,
    area_bigha: 1.66,
    alignment_confidence: 95.8,
    situation: "सही (Verified Clear)",
    reason: "Verified Clear - Undisputed Legal Cadastral Parcel",
    status_color: "green",
  },
  {
    id: "par-114-36",
    khasra_no: "114",
    owner_name: "Khatedar (Kh. 114)",
    village: "Revenue Halqa",
    tehsil: "Central Tehsil",
    alignment_status: "VERIFIED_CLEAR",
    confidence_band: "GREEN",
    ulpin: "ULPIN-UP-2026-114",
    area_sqm: 3990.0,
    area_bigha: 1.58,
    alignment_confidence: 96.2,
    situation: "सही (Verified Clear)",
    reason: "Verified Clear - Undisputed Legal Cadastral Parcel",
    status_color: "green",
  },
];

// Generate synthetic spatial polygon coordinates around base coordinates for all 37 parcels
export function getBenchmark37GeoJSON(): FeatureCollection {
  const baseLat = 26.7605;
  const baseLon = 80.9010;

  const features = BENCHMARK_37_PARCELS.map((p, idx) => {
    const col = idx % 6;
    const row = Math.floor(idx / 6);
    const latOffset = row * 0.0011;
    const lonOffset = col * 0.0014;
    const pLat = baseLat + latOffset;
    const pLon = baseLon + lonOffset;
    const dLat = 0.0008;
    const dLon = 0.0011;

    return {
      type: "Feature" as const,
      properties: {
        id: p.id,
        khasra_no: p.khasra_no,
        owner_name: p.owner_name,
        village: p.village,
        tehsil: p.tehsil,
        alignment_status: p.alignment_status,
        confidence_band: p.confidence_band,
        ulpin: p.ulpin,
        area_sqm: p.area_sqm,
        area_bigha: p.area_bigha,
        alignment_confidence: p.alignment_confidence,
        situation: p.situation,
        reason: p.reason,
        status_color: p.status_color,
      },
      geometry: {
        type: "Polygon" as const,
        coordinates: [
          [
            [pLon, pLat],
            [pLon + dLon, pLat],
            [pLon + dLon, pLat + dLat],
            [pLon, pLat + dLat],
            [pLon, pLat],
          ],
        ],
      },
    };
  });

  return {
    type: "FeatureCollection",
    features,
  };
}

export const BENCHMARK_DEFAULT_METRICS = {
  confidence: 80.0,
  confidenceBand: "AMBER",
  rmseMeters: 0.25,
  keypointsMatched: 42,
  inlierRatio: "92.4%",
  algorithm: "Multi-Modal Structural Edge Correlation & Affine Alignment",
  parcelsHarmonized: 37,
  processingTimeMs: 950,
};

export const BENCHMARK_MAP_FILES = {
  oldMap: {
    name: "cd map 2.jpeg",
    size: "1.42 MB",
    url: "/demo_datasets/mohanlalganj_1974_cadastral_cloth_map.png",
    preview: "/demo_datasets/mohanlalganj_1974_cadastral_cloth_map.png",
  },
  droneMap: {
    name: "drone_orthomosaic.png",
    size: "3.24 MB",
    url: "/demo_datasets/mohanlalganj_drone_orthomosaic.png",
    preview: "/demo_datasets/mohanlalganj_drone_orthomosaic.png",
  },
};

export interface CadastralBlockCoord {
  khasra_no: string;
  nx: number;
  ny: number;
  nw: number;
  nh: number;
  x?: number;
  y?: number;
  w?: number;
  h?: number;
}

export const CADASTRAL_BENCHMARK_BLOCKS: CadastralBlockCoord[] = [
  // Top row
  { khasra_no: "36475", nx: 0.3187, ny: 0.0074, nw: 0.1350, nh: 0.0889 },
  { khasra_no: "1", nx: 0.4797, ny: 0.0556, nw: 0.1203, nh: 0.2296 },
  { khasra_no: "57", nx: 0.7122, ny: 0.1222, nw: 0.0569, nh: 0.0778 },
  { khasra_no: "45454", nx: 0.8488, ny: 0.1667, nw: 0.0569, nh: 0.1111 },

  // Far west & playground
  { khasra_no: "5827269", nx: 0.0049, ny: 0.1444, nw: 0.0504, nh: 0.3037 },
  { khasra_no: "272", nx: 0.2472, ny: 0.1296, nw: 0.0374, nh: 0.2333 },
  { khasra_no: "656565", nx: 0.2846, ny: 0.1074, nw: 0.0959, nh: 0.2741 },

  // School complex
  { khasra_no: "12", nx: 0.4813, ny: 0.3333, nw: 0.0683, nh: 0.1926 },
  { khasra_no: "345", nx: 0.5528, ny: 0.2852, nw: 0.0699, nh: 0.2111 },
  { khasra_no: "123", nx: 0.6260, ny: 0.3444, nw: 0.0602, nh: 0.1259 },

  // Housing Row 1 (upper)
  { khasra_no: "57360", nx: 0.1008, ny: 0.4259, nw: 0.0634, nh: 0.0815 },
  { khasra_no: "895", nx: 0.0715, ny: 0.4444, nw: 0.0293, nh: 0.1185 },
  { khasra_no: "357", nx: 0.1057, ny: 0.5111, nw: 0.1138, nh: 0.0704 },
  { khasra_no: "555", nx: 0.2260, ny: 0.5000, nw: 0.1138, nh: 0.0778 },
  { khasra_no: "777", nx: 0.3463, ny: 0.5037, nw: 0.1106, nh: 0.0667 },

  // Mid-south building wings
  { khasra_no: "144", nx: 0.4829, ny: 0.5667, nw: 0.0488, nh: 0.1556 },
  { khasra_no: "581", nx: 0.5366, ny: 0.5407, nw: 0.0813, nh: 0.1667 },
  { khasra_no: "321", nx: 0.6211, ny: 0.5852, nw: 0.0732, nh: 0.0852 },

  // Eastern housing row 1
  { khasra_no: "610", nx: 0.7073, ny: 0.4815, nw: 0.0797, nh: 0.0593 },
  { khasra_no: "987", nx: 0.8016, ny: 0.4778, nw: 0.0764, nh: 0.0593 },

  // Housing Row 2
  { khasra_no: "987", nx: 0.0732, ny: 0.6296, nw: 0.1154, nh: 0.0667 },
  { khasra_no: "399", nx: 0.2114, ny: 0.6185, nw: 0.1171, nh: 0.0741 },
  { khasra_no: "999", nx: 0.3350, ny: 0.6074, nw: 0.1220, nh: 0.0852 },

  // Housing Row 3
  { khasra_no: "58627", nx: 0.0715, ny: 0.7185, nw: 0.1154, nh: 0.0778 },
  { khasra_no: "69572", nx: 0.2130, ny: 0.7111, nw: 0.1089, nh: 0.0778 },
  { khasra_no: "628", nx: 0.3398, ny: 0.7259, nw: 0.1106, nh: 0.1037 },

  // Far bottom-left & lowest row
  { khasra_no: "555", nx: 0.0049, ny: 0.7741, nw: 0.0504, nh: 0.1778 },
  { khasra_no: "5927", nx: 0.2049, ny: 0.8185, nw: 0.1187, nh: 0.1111 },

  // Bottom Center (Retention Pond)
  { khasra_no: "0", nx: 0.4829, ny: 0.7333, nw: 0.2211, nh: 0.2222 },

  // Eastern complex & residences
  { khasra_no: "233", nx: 0.7041, ny: 0.5519, nw: 0.0927, nh: 0.2037 },
  { khasra_no: "6767", nx: 0.8049, ny: 0.6000, nw: 0.0358, nh: 0.1185 },
  { khasra_no: "25", nx: 0.8992, ny: 0.5333, nw: 0.0293, nh: 0.1889 },
  { khasra_no: "682", nx: 0.9415, ny: 0.5148, nw: 0.0325, nh: 0.1926 },

  // Southeast sports / playground blocks
  { khasra_no: "377", nx: 0.7317, ny: 0.7667, nw: 0.0862, nh: 0.1926 },
  { khasra_no: "222", nx: 0.8228, ny: 0.7778, nw: 0.0504, nh: 0.0556 },
  { khasra_no: "2555", nx: 0.8228, ny: 0.8667, nw: 0.0504, nh: 0.0704 },
  { khasra_no: "888", nx: 0.9106, ny: 0.8185, nw: 0.0488, nh: 0.1667 },
];

export const RED_KHASRA_SET = new Set(["1", "36475", "57", "144", "45454", "895", "6767", "25"]);
export const AMBER_KHASRA_SET = new Set(["272", "345", "581", "123", "12", "610", "357", "777", "321", "233", "682", "58627", "69572", "987"]);


